### ISSUE TITLE
Large data set issue when streaming

### ISSUE THREAD

**Issue by neppinger** [bookchin/boscar#1]
Seeing an issue with a large stream say > 10000 writes 

Code to reproduce: 

```
const boscar = require('boscar');
const stream = require('stream');
function getStream(cb) {
   const nStream = new stream.PassThrough();
   cb(null, nStream);
   for (let i = 0; i < 100000; i++) {
      nStream.write(JSON.stringify({ number: i}));
   }
  nStream.end();
}

const server = new boscar.Server({
  getStream,
});

function getEndLocation(cb) {
  const nStream = new stream.Writable({
    write: (data, enc, callback) => {
      const derp = JSON.parse(data);
      callback();
    },
  });
  cb(null, nStream);
  nStream.on('data', console.log);
  nStream.on('end', () => console.log('end'));
}

const server2 = new boscar.Server({
  getEndLocation,
});

server.listen(5001);
server2.listen(5002);

// initial call to get read stream from one
// main
const client1 = new boscar.Client();
client1.connect(5001);
const client2 = new boscar.Client();
client2.connect(5002);
// initiat call to get read stream from another
client1.invoke('getStream', [], (err, rStream) => {
  client2.invoke('getEndLocation', [], (err2, pStream) => {
    rStream.pipe(pStream);
  });
});
```

**Comment by bookchin** [comment]
There are a few of issues here that are the cause of your problems:

1. Avoid using a `stream.Passthrough` where a `stream.Readable` is more appropriate. This package will work with `stream.Passthrough`s, but they are *always* interpreted as `stream.Readable`'s. This isn't the problem here, just a gotcha to look out for.
2. BOSCAR can handle this amount of data (and much more) just fine, but you are tying up the event loop in your readable stream with that synchronous loop of 100000 writes. Implement a proper readable stream and use `setImmediate` between pushes to free up the event loop.
3. With BOSCAR, your streams have to always be in `objectMode`. This isn't documented, so I'll update the README. This is because of how things get serialized before traveling the wire and deserialized afterwards.
4. A `stream.Writable` doesn't have `data` and `end` events. It has a `finish` event when the readable source is drained.

I have updated your example code to get everything working as you'd expect. Here's the diff:

```diff
4,9c4,19
<    const nStream = new stream.PassThrough();
<    cb(null, nStream);
<    for (let i = 0; i < 100000; i++) {
<       nStream.write(JSON.stringify({ number: i}));
<    }
<   nStream.end();
---
>   let i = 0;
>   const nStream = new stream.Readable({
>     objectMode: true,
>     read() {
>       if (i > 100000) {
>         this.push(null);
>       } else {
>         setImmediate(() => {
>           const data = JSON.stringify({ number: i++ });
>           console.log('reading', data)
>           this.push(data);
>         });
>       }
>     }
>   });
>   cb(null, nStream);
18,19c28,29
<     write: (data, enc, callback) => {
<       const derp = JSON.parse(data);
---
>     write(data, enc, callback) {
>       console.log('writing', data);
21a32
>     objectMode: true
24,25c35
<   nStream.on('data', console.log);
<   nStream.on('end', () => console.log('end'));
---
>   nStream.on('finish', () => console.log('writes finished'));
44c56,61
<     rStream.pipe(pStream);
---
>     rStream.pipe(pStream).on('finish', () => {
>       server.server.close();
>       server2.server.close();
>       client1.socket.destroy();
>       client2.socket.destroy();
>     });

```

You can [download the patch file here](https://gist.githubusercontent.com/bookchin/aa205bfffb2555cf250b3dfbeeef7cf8/raw/bbdad52b137df72fc1f15f3dd5f2374f34075ba8/nathan-boscar-example.patch), then from the directory you have this example:

```
patch example.js nathan-boscar-example.patch 
node example.js
```

That should get it working correctly. Let me know if you have any more issues or questions!

**Comment by neppinger** [comment]
Ok I'll take a look at patching and see if I can get the changes to work with the streams I'm using. Thanks Gordon!
